/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      // ============================================================================
      // 01 PRIMITIVE COLORS (from Figma Variable Collection)
      // ============================================================================
      colors: {
        // Brand (Orange) - Primitive
        brand: {
          50: "#fff7ed",
          100: "#ffedd5",
          200: "#fed7aa",
          300: "#fdba74",
          400: "#fb923c",
          500: "#f97316",
          600: "#ea580c",
          700: "#c2410c",
          800: "#9a3412",
          900: "#7c2d12",
          950: "#431407",
        },
        // Neutral (Slate) - Primitive
        neutral: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cad5e2",
          400: "#90a1b9",
          500: "#62748e",
          600: "#45556c",
          700: "#314158",
          800: "#1d293d",
          900: "#0f172b",
          950: "#020618",
        },
        // Red - Primitive
        red: {
          50: "#fef2f2",
          100: "#ffe2e2",
          200: "#ffc9c9",
          300: "#ffa2a2",
          400: "#ff6467",
          500: "#fb2c36",
          600: "#e7000b",
          700: "#c10007",
          800: "#9f0712",
          900: "#82181a",
          950: "#460809",
        },
        // Amber - Primitive
        amber: {
          50: "#fffbeb",
          100: "#fef3c6",
          200: "#fee685",
          300: "#ffd230",
          400: "#ffb900",
          500: "#fe9a00",
          600: "#e17100",
          700: "#bb4d00",
          800: "#973c00",
          900: "#7b3306",
          950: "#461901",
        },
        // Green - Primitive
        green: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#b9f8cf",
          300: "#7bf1a8",
          400: "#05df72",
          500: "#00c950",
          600: "#00a63e",
          700: "#008236",
          800: "#016630",
          900: "#0d542b",
          950: "#032e15",
        },
        // Blue - Primitive
        blue: {
          50: "#eff6ff",
          100: "#dbeafe",
          200: "#bedbff",
          300: "#8ec5ff",
          400: "#51a2ff",
          500: "#2b7fff",
          600: "#155dfc",
          700: "#1447e6",
          800: "#193cb8",
          900: "#1c398e",
          950: "#162456",
        },
        // Base - Primitive
        base: {
          white: "#ffffff",
          black: "#000000",
          transparent: "rgba(0,0,0,0)",
        },

        // ============================================================================
        // 03 SEMANTIC COLORS - CSS Custom Property References
        // These resolve at runtime via data-theme="light|dark" on <html>
        // ============================================================================
        semantic: {
          // Text colors
          "text-default": "var(--color-text-default)",
          "text-secondary": "var(--color-text-secondary)",
          "text-muted": "var(--color-text-muted)",
          "text-placeholder": "var(--color-text-placeholder)",
          "text-disabled": "var(--color-text-disabled)",
          "text-inverse": "var(--color-text-inverse)",
          "text-brand": "var(--color-text-brand)",
          "text-link": "var(--color-text-link)",
          "text-onBrand": "var(--color-text-onBrand)",
          "text-onStatus": "var(--color-text-onStatus)",
          "text-success": "var(--color-text-success)",
          "text-warning": "var(--color-text-warning)",
          "text-danger": "var(--color-text-danger)",
          "text-information": "var(--color-text-information)",
          // Background colors
          "bg-canvas": "var(--color-bg-canvas)",
          "bg-surface": "var(--color-bg-surface)",
          "bg-elevated": "var(--color-bg-elevated)",
          "bg-subtle": "var(--color-bg-subtle)",
          "bg-inverse": "var(--color-bg-inverse)",
          "bg-disabled": "var(--color-bg-disabled)",
          "bg-brand": "var(--color-bg-brand-default)",
          "bg-brand-hover": "var(--color-bg-brand-hover)",
          "bg-brand-pressed": "var(--color-bg-brand-pressed)",
          "bg-brand-subtle": "var(--color-bg-brand-subtle)",
          "bg-selected": "var(--color-bg-selected)",
          "bg-hover": "var(--color-bg-hover)",
          "bg-pressed": "var(--color-bg-pressed)",
          "bg-danger": "var(--color-bg-danger-default)",
          "bg-danger-subtle": "var(--color-bg-danger-subtle)",
          "bg-success": "var(--color-bg-success-default)",
          "bg-success-subtle": "var(--color-bg-success-subtle)",
          "bg-warning": "var(--color-bg-warning-default)",
          "bg-warning-subtle": "var(--color-bg-warning-subtle)",
          "bg-information": "var(--color-bg-information-default)",
          "bg-information-subtle": "var(--color-bg-information-subtle)",
          // Border colors
          "border-default": "var(--color-stroke-default)",
          "border-subtle": "var(--color-stroke-subtle)",
          "border-strong": "var(--color-stroke-strong)",
          "border-disabled": "var(--color-stroke-disabled)",
          "border-brand": "var(--color-stroke-brand)",
          "border-success": "var(--color-stroke-success)",
          "border-warning": "var(--color-stroke-warning)",
          "border-danger": "var(--color-stroke-danger)",
          "border-information": "var(--color-stroke-information)",
          "border-hover": "var(--color-stroke-hover)",
          "border-focus": "var(--color-stroke-focus)",
        },
      },

      // ============================================================================
      // 02 PRIMITIVE DIMENSIONS (from Figma Variable Collection)
      // ============================================================================
      spacing: {
        0: "0px",
        2: "2px",
        4: "4px",
        6: "6px",
        8: "8px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        32: "32px",
        40: "40px",
        48: "48px",
        64: "64px",
        80: "80px",
        96: "96px",
        128: "128px",
        160: "160px",
      },
      borderRadius: {
        0: "0px",
        2: "2px",
        4: "4px",
        6: "6px",
        8: "8px",
        12: "12px",
        16: "16px",
        24: "24px",
        full: "9999px",
      },
      borderWidth: {
        0: "0px",
        1: "1px",
        2: "2px",
        4: "4px",
      },
      opacity: {
        0: "0",
        4: "0.04",
        8: "0.08",
        12: "0.12",
        16: "0.16",
        24: "0.24",
        32: "0.32",
        40: "0.40",
        48: "0.48",
        64: "0.64",
        80: "0.80",
        100: "1",
      },
      // Fixed sizes (width/height)
      width: {
        8: "8px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        28: "28px",
        32: "32px",
        36: "36px",
        40: "40px",
        44: "44px",
        48: "48px",
        56: "56px",
        64: "64px",
        80: "80px",
        96: "96px",
        120: "120px",
        160: "160px",
      },
      height: {
        8: "8px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        28: "28px",
        32: "32px",
        36: "36px",
        40: "40px",
        44: "44px",
        48: "48px",
        56: "56px",
        64: "64px",
        80: "80px",
        96: "96px",
        120: "120px",
        160: "160px",
      },

      // ============================================================================
      // 04 PRIMITIVE TYPOGRAPHY (from Figma Variable Collection)
      // ============================================================================
      fontSize: {
        11: ["11px", { lineHeight: "16px", letterSpacing: "-0.4px" }],
        12: ["12px", { lineHeight: "16px", letterSpacing: "0px" }],
        14: ["14px", { lineHeight: "20px", letterSpacing: "0px" }],
        16: ["16px", { lineHeight: "24px", letterSpacing: "0px" }],
        18: ["18px", { lineHeight: "28px", letterSpacing: "0px" }],
        20: ["20px", { lineHeight: "28px", letterSpacing: "0px" }],
        24: ["24px", { lineHeight: "32px", letterSpacing: "-0.4px" }],
        28: ["28px", { lineHeight: "36px", letterSpacing: "-0.4px" }],
        32: ["32px", { lineHeight: "40px", letterSpacing: "-0.4px" }],
        40: ["40px", { lineHeight: "48px", letterSpacing: "-0.4px" }],
        48: ["48px", { lineHeight: "56px", letterSpacing: "-0.4px" }],
      },
      fontWeight: {
        regular: "400",
        semibold: "600",
        bold: "700",
        extrabold: "800",
      },
      fontFamily: {
        sans: ["Nunito", "sans-serif"],
      },
      lineHeight: {
        16: "16px",
        20: "20px",
        22: "22px",
        24: "24px",
        28: "28px",
        32: "32px",
        36: "36px",
        40: "40px",
        48: "48px",
        56: "56px",
      },
      letterSpacing: {
        tight: "-0.4px",
        normal: "0px",
        wide: "0.2px",
      },
    },
  },
  plugins: [],
};
